package vue;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * Fenêtre de dialogue pour saisir un nouveau client ou en sélectionner un existant
 * @author ydurand
 * v1.0
 */
public class VueOptionClient extends VueGenerique {    

    /**
     * Creates new dialog VueOptionClient
     */
    public VueOptionClient() {
        initComponents();        
        myInitComponents();
        this.setLocation(500, 200);
    }
    
    //GETTER
    
    
    //Initialisation des comlposants graphiques
    private void myInitComponents() {        
        jLabelTitreDialog = new javax.swing.JLabel();
    }
    
    //Déclaration des variables
    private javax.swing.JLabel jLabelTitreDialog;
    private javax.swing.JButton jButtonRepresentationDetail;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
